version: 2.1
jobs:
  build_test:
    docker:
     - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
    build_docker_image:
      docker:
        - image: circleci/node: 12
      steps:
        - checkout
        - setup remote docker:
            docker layer caching: false
        - run: 
            name: Build Docker image
          command: |
            docker build -t nodejswebapp -t adijaiswal/nodejswebapp: latest .
            echo $DOCKER_ PASSWORD | docker login -u adijalswal -pasaword-stdin
            docker push adijaiawal/nodejawebapp:latest

workflow:
  build_test:
     jobs:
       - build_test
       - build_docker_image
   

      